### ISSUE TITLE
how u use this theme

### ISSUE THREAD

**Issue by PatriotZest** [molecule47/my-i3wm#1]

**Comment by PatriotZest** [comment]
how use this theme? pls tell

**Comment by molecule47** [comment]
if you have i3 (DE) installed, then log onto that create/generate a config file. You can replace the contents with mine (make sure to change directories, etc.) and other things like polybar, rofi have their own configs, you can read up the documentation for each.

**Comment by PatriotZest** [comment]
> if you have i3 (DE) installed, then log onto that create/generate a config file. You can replace the contents with mine (make sure to change directories, etc.) and other things like polybar, rofi have their own configs, you can read up the documentation for each.

alrigt thenks
